services:
  php:
    image: srgiz/blog-unit-php:latest
    restart: unless-stopped
    build:
      context: ./docker/php
    environment:
      PS1: "\\u:\\w$$ "
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/conf.d_ext:/usr/local/etc/php/conf.d"
    volumes:
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d_ext
      - ./:/var/www
    depends_on:
      - database-master
      - database-slave1
      - redis
      #- manticore
      - mailer

  postgres:
    restart: unless-stopped
    build:
      context: ./docker/postgres
    environment:
      POSTGRES_PASSWORD: root # # required by postgres image but not used for init
      PGPASSWORD: root        # for pg_basebackup auth replication user
      PGUSER: replica_user    # for pg_basebackup auth replication user
